
[env]
TERM = "xterm-256color"

[font]
size = 7.5

[font.bold]
family = "JetBrainsMono NF SemiBold"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF SemiBold"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF SemiBold"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF SemiBold"
style = "Regular"

[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
